project:
  type: website
 
website:
  
  title: "Website do Paulo"

  # reader-mode: true
    
  sidebar:
    style: floating
    search: true
    contents:
      - text: "DOUTRINA ESPÍRITA"
        href:
        contents:
          - text: "Grupo de Transição (GT)"
            href: gt.html
          - text: "Estudo Sistematizado"
            href:
      - text: "About"
        href: about.html

  page-footer:
    border: false
    left: "Copyright 2021-2025, Paulo Cunha"
    right: 
      - icon: github
        href: https://github.com/cunhapaulo
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



