---
title: "GT"
about:
  template: solana
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com/cunhapaulo
---

Esta página contém a estrutura programática das reuniões do Grupo de Transição (GT).

| ITEM | TEMA                                      | SUBTEMA                                                                                                                  | BIBLIOGRAFIA                                                                                                                                                                                                                                 |
| ---- | ----------------------------------------- | ------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| I    | **DEUS**                                  | Conceito/Provas da Existência de DEUS.                                                                                   | **LIVRO DOS ESPÍRITOS**: Quest. 1 à 9. **GÊNESE**: Cap. II - Itens [1 a 7].                                                                                                                                                                  |
| II   | **ATRIBUTOS DE DEUS**                     |                                                                                                                          | **LIVRO DOS ESPÍRITOS**: Quest. [10 a 13] - **GÊNESE**: Cap. II - Itens [8 a 19].                                                                                                                                                            |
| III  | **PRECE**                                 | Qualidade / Eficácia / Ação da Prece.                                                                                    | **LIVRO DOS ESPÍRITOS**: Parte 3 – Cap. II. - **EVANGELHO SEGUNDO O ESPIRITISMO**: Cap. XXVII.                                                                                                                                               |
| IV   | **1ª e 2ª REVELAÇÕES DE DEUS AOS HOMENS** | Lei Mosaica e Jesus; Lei de Deus.                                                                                        | **LIVRO DOS ESPÍRITOS**: Cap. I – Item de [1 a 4] e 9.                                                                                                                                                                                       |
| V    | **CRISTIANISMO**                          |                                                                                                                          | **EVANGELHO SEGUNDO O ESPIRITISMO**: Observar as citações evangélicas (ensinamentos); Desenvolver as mais importantes para os participantes deste ciclo.                                                                                     |
| VI   | **3ª REVELAÇÃO DE DEUS AOS HOMENS**       | O Espiritismo como Consolador Prometido; Kardec e as Obas da Codificação (Citações).                                     | **GÊNESE**: Capítulo I; **EVANGELHO SEGUNDO O ESPIRITISMO**: Capítulo I - Item 1 e [5 a 7].                                                                                                                                                  |
| VII  | **ESPÍRITOS**                             | Origem e Natureza dos Espíritos; Mundo Normal e Primitivo; Forma e Ubiquidade dos Espíritos.                             | **LIVRO DOS ESPÍRITOS**: Quest. 76 a 92; - **GÊNESE**: Cap. X - Itens [1 a 9] e [15 a 18].                                                                                                                                                   |
| VIII | **ESPÍRITO, PERISPÍRITO e CORPO**         |                                                                                                                          | **LIVRO DOS ESPÍRITOS**: Quest. [60 a 67] e [76 a 95]; - **GÊNESE**: Cap. X - Itens [26 a 30].                                                                                                                                               |
| IX   | **REENCARNAÇÃO**                          | Conceitos; Objetivos; Justiça; Alma.                                                                                     | **LIVRO DOS ESPÍRITOS**: Quest. [166 a 171] e [132 a 146]; - **GÊNESE**: Cap. XI - Itens [33 e 34].                                                                                                                                          |
| X    | **REENCARNAÇÃO**                          | Lei de Causa e Efeito; Livre Arbítrio.                                                                                   | **LIVRO DOS ESPÍRITOS**: Cap. X - 3a. Parte - Quest. [833 a 850]; O CÉU E O INFERNO: 2ª Parte – Exemplos.                                                                                                                                    |
| XI   | **DESENCARNAÇÃO**                         | A Alma após a Morte; Superação da Alma e do Corpo; Perturbação Espiritual.                                               | **LIVRO DOS ESPÍRITOS**: 3a. Parte - Cap. III - Quest. [149 a 165].                                                                                                                                                                          |
| XII  | **MEDIUNIDADE**                           | Definição e Objetivos; Comentar os tipos mais simples; Eventos mediúnicos narrados nos Evangelhos.                       | **OBRAS PÓSTUMAS**: Pág. [41 a 44] - Itens [1 a 8]; - LIVRO DOS MÉDIUNS: Cap. XIV - itens [159 a 171]; Cap. XV - itens [178 a 181]; - **EVANGELHO SEGUNDO O ESPIRITISMO**: Desenvolver narrações evangélicas que contenham fatos mediúnicos. |
| XIII | **INFLUÊNCIA DOS ESPÍRITOS**              | Ação dos Espíritos: pactos, poder oculto, talismãs, feiticeiros, bençãos e maldições, ocupações e missão dos Espíritos.  | **LIVRO DOS ESPÍRITOS**: Cap. IX - 2a. Parte - Quest. [525 a 535]; Quest. [549 e 550]; Quest. [551 a 557]. Cap. X - 2a. Parte - Quest. [558 a 584].                                                                                          |
| XIV  | **PLURALIDADE DOS MUNDOS HABITADOS**      | Diferentes categorias dos mundos habitados; A Terra como Mundo de Provas e Expiações; A Terra como Mundo de Regeneração. | **EVANGELHO SEGUNDO O ESPIRITISMO**: Cap. III - Itens [3 a 5] e [6 a 7]; Itens [8 e 9] e [16 a 18]; - **LIVRO DOS ESPÍRITOS**: Quest. [55 a 59].                                                                                             |
| XV   | **O EVANGELHO NO LAR**                    | Motivações, Benefícios, Forma, Orientações.                                                                              |                                                                                                                                                                                                                                              |
